// <auto-generated />
using System;
using GymApp.API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GymApp.API.Migrations
{
    [DbContext(typeof(GymAppDbContext))]
    partial class GymAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("GymApp.Domain.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<float>("ClientWeight")
                        .HasColumnType("real");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<long?>("NutritionPlanId")
                        .HasColumnType("bigint");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("NutritionPlanId");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("GymApp.Domain.ExercisePlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("ExercisesType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ExercisesType")
                        .IsUnique();

                    b.ToTable("ExercisePlans");
                });

            modelBuilder.Entity("GymApp.Domain.Meal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long?>("MealId")
                        .HasColumnType("bigint");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.HasIndex("MealName")
                        .IsUnique();

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("GymApp.Domain.NutritionPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("NutritionType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("NutritionType")
                        .IsUnique();

                    b.ToTable("NutritionPlans");
                });

            modelBuilder.Entity("GymApp.Domain.NutritionPlanMeal", b =>
                {
                    b.Property<long>("MealId")
                        .HasColumnType("bigint");

                    b.Property<long>("NutritionPlanId")
                        .HasColumnType("bigint");

                    b.HasKey("MealId", "NutritionPlanId");

                    b.HasIndex("NutritionPlanId");

                    b.ToTable("NutritionPlanMeals");
                });

            modelBuilder.Entity("GymApp.Domain.Trainer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Experience")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Trainers");
                });

            modelBuilder.Entity("GymApp.Domain.WorkoutClass", b =>
                {
                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<long>("TrainerId")
                        .HasColumnType("bigint");

                    b.Property<long>("ExercisePlanId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ClientId", "TrainerId");

                    b.HasIndex("ExercisePlanId");

                    b.HasIndex("TrainerId");

                    b.ToTable("WorkoutClasses");
                });

            modelBuilder.Entity("GymApp.Domain.Client", b =>
                {
                    b.HasOne("GymApp.Domain.NutritionPlan", "NutritionPlan")
                        .WithMany()
                        .HasForeignKey("NutritionPlanId")
                        .HasConstraintName("FK__Clients__Nutriti__4D94879B")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("NutritionPlan");
                });

            modelBuilder.Entity("GymApp.Domain.Meal", b =>
                {
                    b.HasOne("GymApp.Domain.Meal", null)
                        .WithMany("NutritionPlanMeals")
                        .HasForeignKey("MealId");
                });

            modelBuilder.Entity("GymApp.Domain.NutritionPlanMeal", b =>
                {
                    b.HasOne("GymApp.Domain.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymApp.Domain.NutritionPlan", "NutritionPlan")
                        .WithMany("NutritionPlanMeals")
                        .HasForeignKey("NutritionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("NutritionPlan");
                });

            modelBuilder.Entity("GymApp.Domain.WorkoutClass", b =>
                {
                    b.HasOne("GymApp.Domain.Client", "Client")
                        .WithMany("WorkoutClasses")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymApp.Domain.ExercisePlan", "ExercisePlan")
                        .WithMany()
                        .HasForeignKey("ExercisePlanId")
                        .HasConstraintName("FK__WorkoutCl__Exerc__5535A963")
                        .IsRequired();

                    b.HasOne("GymApp.Domain.Trainer", "Trainer")
                        .WithMany("WorkoutClasses")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ExercisePlan");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("GymApp.Domain.Client", b =>
                {
                    b.Navigation("WorkoutClasses");
                });

            modelBuilder.Entity("GymApp.Domain.Meal", b =>
                {
                    b.Navigation("NutritionPlanMeals");
                });

            modelBuilder.Entity("GymApp.Domain.NutritionPlan", b =>
                {
                    b.Navigation("NutritionPlanMeals");
                });

            modelBuilder.Entity("GymApp.Domain.Trainer", b =>
                {
                    b.Navigation("WorkoutClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
